"""
Security regression tests for the hardening work.

Run from backend/:
    python -m pytest tests/test_security.py -v
"""
import bcrypt
import pytest

from app.core import security as sec
from app.core.config import Settings, _enforce_secret_key, _INSECURE_DEFAULT_KEY

from conftest import auth_headers, make_user

API = "/api/v1"


# ── Password hashing ────────────────────────────────────────────────────────

def test_hash_and_verify_roundtrip():
    h = sec.get_password_hash("Testpass1")
    assert sec.verify_password("Testpass1", h)
    assert not sec.verify_password("Wrongpass1", h)


def test_long_passwords_not_truncated_at_72_bytes():
    """Two passwords identical for 72 bytes but differing after must NOT collide
    (the SHA-256 pre-hash fixes bcrypt's silent truncation)."""
    base = "A" * 72
    h = sec.get_password_hash(base + "first-tail")
    assert sec.verify_password(base + "first-tail", h)
    assert not sec.verify_password(base + "second-tail", h)


def test_legacy_direct_bcrypt_hash_still_verifies():
    """Accounts created before the pre-hash change must still log in."""
    legacy = bcrypt.hashpw("Testpass1".encode("utf-8")[:72], bcrypt.gensalt()).decode()
    assert sec.verify_password("Testpass1", legacy)


def test_dummy_verify_runs_without_error():
    sec.dummy_verify()  # must not raise


# ── SECRET_KEY enforcement ──────────────────────────────────────────────────

def test_secret_key_weak_in_production_raises(monkeypatch):
    s = Settings(SECRET_KEY=_INSECURE_DEFAULT_KEY, ENV="production")
    with pytest.raises(RuntimeError):
        _enforce_secret_key(s)


def test_secret_key_empty_in_production_raises():
    s = Settings(SECRET_KEY="", ENV="production")
    with pytest.raises(RuntimeError):
        _enforce_secret_key(s)


def test_secret_key_strong_in_production_ok():
    s = Settings(SECRET_KEY="x" * 48, ENV="production")
    _enforce_secret_key(s)  # must not raise


def test_secret_key_autogenerated_in_dev():
    s = Settings(SECRET_KEY="", ENV="development")
    _enforce_secret_key(s)
    assert s.SECRET_KEY and len(s.SECRET_KEY) >= 32


# ── Login enumeration ───────────────────────────────────────────────────────

def test_login_unknown_user_generic_error(client):
    r = client.post(f"{API}/auth/login",
                    json={"username": "ghost_acct_xyz", "password": "Whatever1"})
    assert r.status_code == 400
    assert r.json()["detail"] == "Incorrect username or password"


def test_login_wrong_password_same_error(client, db):
    make_user(db, "enum_user")
    r = client.post(f"{API}/auth/login",
                    json={"username": "enum_user", "password": "Wrongpass9"})
    assert r.status_code == 400
    # Identical message to the unknown-user case → no enumeration via content.
    assert r.json()["detail"] == "Incorrect username or password"


# ── Single-use reset tokens ─────────────────────────────────────────────────

def test_reset_token_is_single_use(client, db):
    user = make_user(db, "single_use_user")
    token = sec.create_reset_token(user.username)

    r1 = client.post(f"{API}/auth/reset-password",
                     json={"token": token, "new_password": "Newpass123"})
    assert r1.status_code == 200

    # Same token again → rejected (password_changed_at now newer than token iat)
    r2 = client.post(f"{API}/auth/reset-password",
                     json={"token": token, "new_password": "Another123"})
    assert r2.status_code == 400


# ── Security headers ────────────────────────────────────────────────────────

def test_security_headers_present(client):
    r = client.get(f"{API}/../")  # any response goes through middleware
    # Use a known route instead:
    r = client.post(f"{API}/auth/login", json={"username": "x", "password": "y"})
    h = r.headers
    assert "content-security-policy" in {k.lower() for k in h.keys()}
    assert h.get("X-Frame-Options") == "DENY"
    assert h.get("X-Content-Type-Options") == "nosniff"
    assert "Permissions-Policy" in h


def test_csp_blocks_framing_and_objects(client):
    r = client.post(f"{API}/auth/login", json={"username": "x", "password": "y"})
    csp = r.headers.get("Content-Security-Policy", "")
    assert "frame-ancestors 'none'" in csp
    assert "object-src 'none'" in csp
    assert "base-uri 'self'" in csp


# ── Request body size limit ─────────────────────────────────────────────────

def test_oversized_body_rejected(client):
    # Declare a huge Content-Length; middleware should 413 before parsing.
    big = "a" * 5000
    r = client.post(
        f"{API}/auth/login",
        data=big,
        headers={"Content-Type": "application/json", "Content-Length": str(2 * 1024 * 1024)},
    )
    assert r.status_code == 413
