from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel
import random
import time
from app.core.puzzle_store import store_solution, get_solution, remove_solution, get_generation_time
from app.core.security import create_solve_token

try:
    from slowapi import Limiter
    from slowapi.util import get_remote_address
    limiter = Limiter(key_func=get_remote_address)
except ImportError:
    limiter = None

def _rate_limit(limit_string):
    def decorator(func):
        if limiter is not None:
            return limiter.limit(limit_string)(func)
        return func
    return decorator

router = APIRouter(prefix="/games/wordle", tags=["wordle"])

# Curated list of common 5-letter English words
WORD_LIST = [
    "about", "above", "actor", "acute", "admit", "adopt", "adult", "after", "again", "agent",
    "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone", "along",
    "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena", "argue",
    "arise", "array", "arrow", "aside", "asset", "audio", "audit", "avoid", "award", "aware",
    "awful", "badly", "baker", "bases", "basic", "basis", "beach", "beard", "beast", "begin",
    "being", "below", "bench", "berry", "birth", "black", "blade", "blame", "blank", "blast",
    "blend", "blind", "block", "blood", "board", "boast", "bonus", "boost", "bound", "brain",
    "brand", "bread", "break", "breed", "brick", "bride", "brief", "bring", "broad", "broke",
    "brown", "brush", "build", "built", "bunch", "buyer", "cable", "calmly", "camel", "camera",
    "camp", "canal", "candy", "canon", "cargo", "carve", "case", "catch", "cater", "cause",
    "cedar", "chain", "chair", "chalk", "champ", "chant", "chaos", "charm", "chart", "chase",
    "cheap", "cheat", "check", "cheek", "cheer", "chess", "chest", "chief", "child", "chime",
    "china", "chips", "choir", "chunk", "cider", "cigar", "claim", "clash", "clasp", "class",
    "clean", "clear", "clerk", "click", "cliff", "climb", "clock", "close", "cloth", "cloud",
    "clown", "coach", "coast", "cobra", "cocoa", "colt", "column", "comet", "comic", "comma",
    "coral", "couch", "cough", "could", "count", "court", "cover", "coyly", "craft", "crane",
    "crank", "crash", "crass", "crate", "crave", "crawl", "craze", "crazy", "cream", "creed",
    "creek", "creep", "crept", "crest", "crick", "cried", "crier", "crime", "crimp", "crisp",
    "crook", "crop", "cross", "crowd", "crown", "crude", "cruel", "crumb", "crush", "crust",
    "crypt", "cubic", "cumin", "curry", "curse", "curve", "cycle", "cynic", "daddy", "daily",
    "dairy", "daisy", "dance", "dandy", "datum", "dawn", "dazzle", "dealt", "death", "debit",
    "debug", "debut", "decaf", "decal", "decay", "decor", "decoy", "decry", "defer", "delay",
    "delta", "demon", "demur", "denim", "dense", "depot", "depth", "derby", "detox", "deuce",
    "devil", "diary", "dice", "digit", "diner", "dingo", "dingy", "dinky", "diode", "dirge",
    "dirty", "disco", "ditch", "ditto", "ditty", "diver", "dizzy", "dodge", "dodgy", "dogma",
    "doing", "dolly", "donor", "donut", "doom", "door", "dopey", "dose", "double", "doubt",
    "dough", "douse", "dove", "dowdy", "dowel", "downy", "dowry", "dozen", "draft", "drag",
    "drain", "drake", "drama", "drank", "drape", "draw", "drawl", "drawn", "dread", "dream",
    "dregs", "dress", "dried", "drier", "drift", "drill", "drink", "drip", "drive", "droll",
    "drone", "drool", "droop", "drop", "dross", "drove", "drown", "drub", "drug", "drum",
    "drunk", "dryly", "duchy", "dully", "dummy", "dumpy", "dunce", "dune", "dupe", "duplicity",
    "dusk", "dusky", "dust", "dusty", "dutch", "dwarf", "dwell", "dwelt", "dying", "eager",
    "eagle", "early", "earth", "ease", "easel", "east", "eaten", "eater", "ebony", "eclat",
    "echo", "eddy", "edge", "edgy", "eerie", "egotism", "eight", "eject", "eking", "elate",
    "elbow", "elder", "elect", "elegy", "elfin", "elicit", "elite", "elope", "elude", "email",
    "embed", "ember", "emery", "emit", "emoji", "emperor", "empire", "empty", "enact", "endow",
    "enema", "enemy", "enjoy", "ennui", "enrol", "ensue", "enter", "entry", "envoy", "epoch",
    "epoxy", "equal", "equip", "erase", "erect", "erode", "error", "erupt", "essay", "ester",
    "ether", "ethic", "ethos", "etude", "evade", "even", "event", "every", "evict", "evil",
    "evoke", "exact", "exalt", "exam", "excel", "exert", "exile", "exist", "exit", "expel",
    "extol", "extra", "exult", "eying", "fable", "face", "facet", "fact", "factor", "fade",
    "fading", "fail", "faint", "fair", "fairy", "faith", "fake", "falcon", "fall", "false",
    "fame", "fancy", "fang", "farce", "fare", "farm", "fast", "fatal", "fate", "father",
    "fault", "faun", "favor", "fawn", "fear", "feast", "feat", "feces", "fed", "feed",
    "feel", "feet", "feign", "feint", "feline", "fell", "felon", "felt", "femur", "fence",
    "fend", "feral", "ferry", "fetal", "fetch", "fetid", "fetus", "feud", "fever", "fewer",
    "fiber", "fibre", "fief", "field", "fiend", "fiery", "fifth", "fifty", "fight", "figure",
    "file", "filet", "fill", "film", "filmy", "filter", "filth", "final", "finance", "find",
    "fine", "finery", "finger", "finis", "finish", "finite", "finned", "fire", "firm",
    "first", "fish", "fishy", "fist", "fit", "five", "fix", "fixed", "fixer", "fizzy",
    "fjord", "flack", "flag", "flail", "flair", "flake", "flaky", "flame", "flank", "flare",
    "flash", "flask", "flat", "flatter", "flaw", "flawless", "flawy", "flax", "flea",
    "fleck", "fled", "flee", "fleet", "flesh", "fleshy", "flew", "flex", "flick", "flier",
    "flight", "flimsy", "flinch", "fling", "flint", "flinty", "flip", "flirt", "float",
    "flock", "flog", "flood", "floor", "flop", "flora", "floss", "flour", "flow", "flown",
    "flue", "fluff", "fluffy", "fluid", "fluke", "fluky", "flume", "flung", "flunk", "flush",
    "flute", "flutter", "flux", "flyer", "foal", "foam", "foamy", "focal", "focus", "fog",
    "foggy", "foil", "foist", "fold", "folder", "folk", "folly", "fond", "fondly", "font",
    "food", "fool", "foot", "forage", "foray", "force", "ford", "fore", "forest", "forge",
    "forget", "forgo", "fork", "form", "formal", "format", "former", "fort", "forte",
    "forth", "forty", "forum", "forward", "foss", "fossil", "foster", "fought", "foul",
    "found", "fount", "four", "fowling", "fox", "foyer", "fracas", "fraction", "fracture",
    "fragile", "frame", "frank", "frantic", "fraud", "fray", "freak", "free", "freed",
    "freely", "freeze", "freight", "french", "frenzy", "frequent", "fresh", "fret",
    "friction", "friend", "fright", "frigid", "frill", "fringe", "frock", "frog", "frolic",
    "from", "front", "frost", "frosty", "froth", "frothy", "frown", "froze", "frozen",
    "frugal", "fruit", "fruity", "frump", "fryer", "fudge", "fuel", "fugitive", "fugue",
    "full", "fully", "fumble", "fume", "fumigate", "fun", "function", "fund", "funeral",
    "fungal", "fungi", "funky", "funnel", "funny", "fur", "furious", "furl", "furlong",
    "furnace", "furor", "furrow", "furry", "further", "fury", "fuse", "fusion", "fuss",
    "fussy", "futile", "future", "fuzzy", "gabby", "gable", "gadget", "gaffe", "gaily",
    "gain", "gait", "gala", "galaxy", "gale", "gall", "galleon", "gallery", "galley",
    "gallon", "gallop", "gallows", "gamut", "gang", "gaol", "gape", "garage", "garb",
    "garbage", "garden", "gargle", "garland", "garlic", "garment", "garter", "gas",
    "gaseous", "gash", "gasp", "gastric", "gate", "gather", "gaudy", "gauge", "gaunt",
    "gauze", "gavel", "gawk", "gawky", "gay", "gaze", "gazette", "gear", "gelatin",
    "gem", "gender", "gene", "general", "generate", "generous", "genesis", "genie",
    "genius", "genre", "gentle", "gently", "genuine", "genus", "geography", "geology",
    "geometry", "germ", "gesture", "get", "geyser", "ghastly", "ghetto", "ghost",
    "giant", "gibbet", "giddy", "gift", "gig", "gigantic", "giggle", "gild", "gill",
    "gilt", "gimlet", "gimmick", "gin", "ginger", "gipsy", "gird", "girdle", "girl",
    "girth", "gist", "give", "given", "giver", "glacial", "glacier", "glad", "glade",
    "gladiator", "glamour", "glance", "gland", "glare", "glass", "glassy", "glaze",
    "gleam", "glean", "glee", "glen", "glib", "glide", "glimmer", "glimpse", "glint",
    "glisten", "glitter", "gloat", "globe", "gloom", "gloomy", "glorify", "glorious",
    "glory", "gloss", "glossary", "glossy", "glove", "glow", "glower", "glowworm",
    "glucose", "glue", "glug", "glum", "glut", "gluten", "glutton", "glycerin", "gnarl",
    "gnash", "gnat", "gnaw", "gneiss", "goad", "goal", "goat", "gobble", "goblet",
    "goblin", "god", "goddess", "godfather", "godly", "godsend", "goggle", "going",
    "gold", "golden", "goldfish", "golf", "gondola", "gong", "good", "goodbye",
    "goodly", "goodness", "goods", "goose", "gooseberry", "gopher", "gorge",
    "gorgeous", "gorilla", "gory", "goshawk", "gosling", "gospel", "gossamer",
    "gossip", "got", "goth", "gothic", "gouge", "gourd", "gout", "govern",
    "governess", "government", "governor", "gown", "grab", "grace", "graceful",
    "gracious", "grade", "gradient", "gradual", "graduate", "graft", "grain",
    "gram", "grammar", "granary", "grand", "grandchild", "grandeur", "grandfather",
    "grandmother", "grandson", "granite", "grant", "grape", "grapefruit", "graph",
    "grapnel", "grapple", "grasp", "grass", "grasshopper", "grate", "grateful",
    "gratify", "grating", "gratis", "gratitude", "grave", "gravel", "gravity",
    "gravy", "gray", "graze", "grease", "greasy", "great", "greatly", "grebe",
    "grecian", "greed", "greedy", "green", "greenhouse", "greet", "gregarious",
    "grenade", "grew", "grey", "greyhound", "grid", "griddle", "grief",
    "grievance", "grieve", "grievous", "griffin", "grill", "grim", "grimace",
    "grime", "grimy", "grin", "grind", "grindstone", "grip", "gripe", "grisly",
    "grist", "gristle", "grit", "gritty", "grizzly", "groan", "grocer",
    "grocery", "groggy", "groin", "groom", "groove", "grope", "grosbeak",
    "gross", "grotesque", "grotto", "ground", "groundsel", "group", "grouse",
    "grove", "grovel", "grow", "growl", "grown", "growth", "grub", "grudge",
    "gruel", "gruesome", "gruff", "grumble", "grunt", "guano", "guarantee",
    "guard", "guardian", "guava", "gudgeon", "guerilla", "guess", "guest",
    "guffaw", "guidance", "guide", "guild", "guile", "guileless", "guillotine",
    "guilt", "guilty", "guinea", "guise", "guitar", "gulf", "gull", "gullet",
    "gully", "gulp", "gum", "gumboil", "gumption", "gun", "gunboat", "gunner",
    "gunpowder", "gurgle", "gush", "gusher", "gust", "gusty", "gut", "gutter",
    "gymnast", "gypsum", "gypsy", "gyrate", "habit", "habitat", "habitual",
    "hackney", "haddock", "haemorrhage", "haggard", "haggle", "hail",
    "hailstone", "hair", "hairdresser", "hairy", "halberd", "halcyon", "hale",
    "half", "halibut", "hall", "hallelujah", "hallmark", "hallow", "hallucination",
    "halo", "halt", "halter", "halve", "hamlet", "hammer", "hammock", "hamper",
    "hand", "handcuff", "handicap", "handicraft", "handiwork", "handkerchief",
    "handle", "handsome", "handwriting", "handy", "hang", "hangar", "hanger",
    "hangman", "hanker", "haphazard", "hapless", "happen", "happiness", "happy",
    "harangue", "harass", "harbinger", "harbor", "harbour", "hard", "harden",
    "hardihood", "hardly", "hardness", "hardship", "hardware", "hardy", "hare",
    "harebell", "harem", "haricot", "hark", "harlequin", "harm", "harmful",
    "harmless", "harmonious", "harmonize", "harmony", "harness", "harp",
    "harpoon", "harpsichord", "harpy", "harrier", "harrow", "harry", "harsh",
    "hart", "harvest", "hash", "haste", "hasten", "hasty", "hat", "hatch",
    "hatchet", "hate", "hateful", "hatred", "haughty", "haul", "haunch",
    "haunt", "have", "haven", "havoc", "hawk", "hawthorn", "hay", "hazard",
    "hazardous", "haze", "hazel", "hazelnut", "hazy", "head", "headache",
    "heading", "headland", "headlong", "headquarters", "heady", "heal",
    "health", "healthy", "heap", "hear", "hearken", "hearsay", "hearse",
    "heart", "hearth", "hearty", "heat", "heater", "heath", "heathen",
    "heather", "heating", "heave", "heaven", "heavenly", "heavy", "hebrew",
    "hecatomb", "hectic", "hedge", "hedgehog", "heed", "heedless", "heel",
    "hegemony", "heifer", "height", "heighten", "heinous", "heir", "heiress",
    "held", "helicopter", "heliotrope", "helix", "hell", "hellebore",
    "hellenic", "helm", "helmet", "helmsman", "help", "helpful", "helpless",
    "helpmate", "helter-skelter", "hem", "hemisphere", "hemlock", "hemp",
    "hen", "henbane", "hence", "henceforth", "henchman", "herald", "herb",
    "herbage", "herculean", "herd", "herdsman", "here", "hereafter", "hereby",
    "hereditary", "heredity", "herein", "heresy", "heretic", "heretofore",
    "herewith", "heritage", "hermaphrodite", "hermit", "hermitage", "hero",
    "heroic", "heroine", "heroism", "heron", "herring", "hesitate", "hesitation",
    "heterodox", "heterogeneous", "hew", "hexagon", "heyday", "hiatus",
    "hibernate", "hiccough", "hickory", "hidden", "hide", "hideous",
    "hierarchy", "hieroglyphic", "high", "highland", "highly", "highway",
    "highwayman", "hike", "hilarious", "hilarity", "hill", "hillock", "hilly",
    "hilt", "hind", "hinder", "hindrance", "hindu", "hinge", "hint",
    "hip", "hippopotamus", "hire", "hireling", "hiss", "historian", "historic",
    "historical", "history", "hit", "hitch", "hither", "hitherto", "hive",
    "hoar", "hoard", "hoarfrost", "hoarse", "hoary", "hoax", "hobble",
    "hobby", "hobgoblin", "hobnail", "hock", "hockey", "hod", "hoe", "hog",
    "hogshead", "hoist", "hold", "holder", "holding", "hole", "holiday",
    "holiness", "holland", "hollow", "holly", "hollyhock", "holocaust",
    "holster", "holy", "homage", "home", "homely", "homeopathy", "homesick",
    "homespun", "homestead", "homeward", "homicide", "homily", "homogeneous",
    "hone", "honest", "honesty", "honey", "honeycomb", "honeymoon", "honeysuckle",
    "honor", "honorable", "honorary", "honour", "hood", "hoof", "hook",
    "hoop", "hoot", "hop", "hope", "hopeful", "hopeless", "horde", "horizon",
    "horizontal", "horn", "hornet", "horny", "horoscope", "horrible",
    "horrid", "horrify", "horror", "horse", "horseback", "horsebox",
    "horseman", "horseshoer", "hose", "hosiery", "hospitable", "hospital",
    "hospitality", "host", "hostage", "hostel", "hostess", "hostile",
    "hostility", "hot", "hotel", "hotbed", "hothouse", "hound", "hour",
    "house", "householder", "housewife", "hovel", "hover", "how", "howitzer",
    "howl", "hub", "huckleberry", "huddle", "hue", "huff", "hug", "huge",
    "hulk", "hull", "hum", "human", "humane", "humanist", "humanity",
    "humble", "humbug", "humdrum", "humid", "humidity", "humiliate",
    "humiliation", "humility", "hummingbird", "humor", "humorous", "humour",
    "hump", "humpback", "humus", "hunch", "hunchback", "hundred", "hung",
    "hunger", "hungry", "hunt", "hunter", "huntsman", "hurdle", "hurl",
    "hurricane", "hurry", "hurt", "hurtful", "husband", "husbandry", "hush",
    "husk", "husky", "hussar", "hustle", "hut", "hyacinth", "hybrid",
    "hydra", "hydrangea", "hydrant", "hydraulic", "hydrogen", "hydrophobia",
    "hyena", "hygiene", "hygrometer", "hymn", "hyperbola", "hyphen",
    "hypochondria", "hypocrisy", "hypocrite", "hypotenuse", "hypothesis",
    "hyssop", "hysteria", "hysterical", "iambic", "ibex", "ibis", "ice",
    "iceberg", "ichneumon", "icicle", "icy", "idea", "ideal", "idealist",
    "idealize", "identical", "identify", "identity", "idiom", "idiomatic",
    "idiot", "idiotic", "idle", "idler", "idly", "idol", "idolatry",
    "idolize", "idyll", "if", "igneous", "ignite", "ignoble", "ignominious",
    "ignominy", "ignorance", "ignorant", "ignore", "ill", "illegal",
    "illegible", "illegitimate", "illicit", "illiterate", "illness",
    "illuminate", "illusion", "illusory", "illustrate", "illustration",
    "illustrious", "image", "imagery", "imaginary", "imagination", "imagine",
    "imbecile", "imbue", "imitate", "imitation", "immaculate", "immanent",
    "immaterial", "immature", "immeasurable", "immediate", "immemorial",
    "immense", "immensity", "immerse", "immigrant", "immigrate", "imminent",
    "immobile", "immoderate", "immodest", "immolate", "immoral", "immortal",
    "immortality", "immovable", "immunity", "immunize", "immure", "immutable",
    "imp", "impact", "impair", "impale", "impalpable", "impart", "impartial",
    "impassable", "impassioned", "impassive", "impatience", "impatient",
    "impeach", "impeccable", "impede", "impediment", "impel", "impend",
    "impenitent", "imperative", "imperceptible", "imperfect", "imperial",
    "imperialism", "imperious", "imperishable", "impersonate", "impertinent",
    "impervious", "impetuous", "impetus", "impiety", "impinge", "impious",
    "implacable", "implant", "implement", "implicate", "implicit", "implore",
    "imply", "impolite", "impolitic", "import", "importance", "important",
    "importunate", "importune", "impose", "imposing", "impossible", "impostor",
    "imposture", "impotent", "impound", "impoverish", "impracticable",
    "imprecation", "impregnable", "impregnate", "impress", "impression",
    "impressive", "imprint", "imprison", "improbable", "impromptu",
    "improper", "impropriety", "improve", "improvement", "improvident",
    "improvise", "imprudent", "impudent", "impugn", "impulse", "impulsive",
    "impunity", "impure", "impurity", "impute", "in", "inability",
    "inaccessible", "inaccurate", "inaction", "inactive", "inadequate",
    "inadmissible", "inadvertent", "inalienable", "inane", "inanimate",
    "inapplicable", "inappreciable", "inappropriate", "inarticulate",
    "inartistic", "inasmuch", "inattention", "inaudible", "inaugurate",
    "inborn", "inbred", "incalculable", "incandescence", "incantation",
    "incapable", "incapacitate", "incapacity", "incarcerate", "incarnate",
    "incarnation", "incautious", "incendiary", "incense", "incentive",
    "inception", "incessant", "inch", "incidence", "incident", "incidental",
    "incinerator", "incipient", "incise", "incision", "incite", "incivility",
    "inclement", "inclination", "incline", "include", "inclusive", "incognito",
    "incoherent", "income", "incommode", "incomparable", "incompatible",
    "incompetent", "incomplete", "incomprehensible", "inconceivable",
    "incongruous", "inconsequent", "inconsiderable", "inconsiderate",
    "inconsistent", "inconsolable", "inconspicuous", "inconstant",
    "incontestable", "incontinent", "incontrovertible", "inconvenience",
    "inconvenient", "incorporate", "incorporeal", "incorrect", "incorrigible",
    "incorruptible", "increase", "incredible", "incredulous", "increment",
    "incriminate", "incrust", "incubate", "incubator", "incubus", "inculcate",
    "incumbency", "incumbent", "incur", "incurable", "incurious", "incursion",
    "indebted", "indecent", "indecision", "indecisive", "indeclinable",
    "indecorous", "indeed", "indefatigable", "indefensible", "indefinite",
    "indelible", "indelicacy", "indelicate", "indemnify", "indemnity",
    "indent", "indenture", "independence", "independent", "indescribable",
    "indestructible", "indeterminate", "index", "india", "indian", "indicate",
    "indicative", "indict", "indifference", "indifferent", "indigence",
    "indigenous", "indigent", "indigestible", "indigestion", "indignant",
    "indignation", "indigo", "indirect", "indiscreet", "indiscretion",
    "indiscriminate", "indispensable", "indisposed", "indisposition",
    "indisputable", "indissoluble", "indistinct", "indistinguishable",
    "indite", "individual", "individuality", "indivisible", "indolence",
    "indolent", "indomitable", "indoor", "indorse", "indubitable", "induce",
    "inducement", "induct", "induction", "indulge", "indulgence", "indulgent",
    "industrial", "industrious", "industry", "inebriate", "ineffable",
    "ineffective", "ineffectual", "inefficient", "inelegant", "ineligible",
    "inelutable", "inept", "inequality", "inequitable", "inert", "inertia",
    "inestimable", "inevitable", "inexact", "inexcusable", "inexhaustible",
    "inexorable", "inexpedient", "inexpensive", "inexperience", "inexpert",
    "inexpiable", "inexplicable", "inexpressible", "inexpressive",
    "inextricable", "infallible", "infamous", "infamy", "infancy", "infant",
    "infantry", "infatuate", "infect", "infection", "infectious", "infelicity",
    "infer", "inference", "inferior", "inferiority", "infernal", "inferno",
    "infest", "infidel", "infidelity", "infinite", "infinitesimal",
    "infinitive", "infinity", "infirm", "infirmary", "infirmity", "inflame",
    "inflammable", "inflammation", "inflammatory", "inflate", "inflation",
    "inflect", "inflection", "inflexible", "inflict", "influence",
    "influential", "influenza", "influx", "inform", "informal", "informant",
    "information", "informer", "infraction", "infrequent", "infringe",
    "infuriate", "infuse", "infusion", "ingenious", "ingenuity", "ingenuous",
    "inglorious", "ingot", "ingraft", "ingratiate", "ingratitude",
    "ingredient", "ingress", "inhabit", "inhabitant", "inhale", "inherent",
    "inherit", "inheritance", "inheritor", "inhibit", "hospitable",
    "hostile", "human", "humble", "hurt", "husband", "hush", "hybrid",
    "hymn", "hyphen", "ice", "idea", "ideal", "idiot", "idle", "idol",
    "ill", "image", "imp", "index", "ink", "inn", "input", "iron",
    "island", "issue", "itch", "item", "ivory", "jackal", "jacket", "jade",
    "jail", "jam", "jar", "jasmine", "javelin", "jaw", "jay", "jazz",
    "jealous", "jeep", "jelly", "jerk", "jersey", "jest", "jet", "jewel",
    "jibe", "jig", "jilt", "jingle", "job", "jockey", "jocund", "jog",
    "join", "joint", "joke", "jolly", "jolt", "jonquil", "journal", "journey",
    "joust", "jovial", "joy", "joyful", "joyous", "jubilant", "jubilee",
    "judge", "judgment", "judicial", "jug", "juggle", "juice", "juicy",
    "july", "jumble", "jump", "jumper", "junction", "june", "jungle",
    "junior", "juniper", "junk", "junta", "jurisdiction", "juror", "jury",
    "just", "justice", "justify", "jut", "jute", "juvenile", "kangaroo",
    "kaolin", "keel", "keen", "keep", "keeper", "keepsake", "keg",
    "kelp", "kennel", "kept", "kernel", "kerosene", "kestrel", "kettle",
    "key", "keyboard", "keyhole", "keystone", "khaki", "kick", "kid",
    "kidnap", "kidney", "kill", "kiln", "kilt", "kimono", "kin",
    "kind", "kindle", "kindly", "kindness", "kindred", "king", "kingdom",
    "kingfisher", "kinsman", "kiosk", "kiss", "kit", "kitchen", "kite",
    "kitten", "knack", "knapsack", "knave", "knead", "knee", "kneel",
    "knell", "knelt", "knew", "knickerbockers", "knife", "knight", "knit",
    "knitch", "knob", "knock", "knocker", "knoll", "knot", "knotty",
    "know", "knowledge", "known", "knuckle", "koran", "label", "laboratory",
    "laborious", "labour", "labyrinth", "lace", "lacerate", "lack",
    "lackey", "laconic", "lacquer", "lad", "ladder", "lade", "laden",
    "ladle", "lady", "ladybird", "ladybird", "lag", "lagoon", "laity",
    "lake", "lamb", "lame", "lament", "lamentable", "lamp", "lampoon",
    "lamprey", "lance", "lancer", "land", "landlord", "landmark", "landscape",
    "landslide", "lane", "language", "languid", "languish", "languor",
    "lank", "lanky", "lantern", "lap", "lapel", "lapse", "lapwing",
    "larboard", "larceny", "larch", "lard", "larder", "large", "largely",
    "lark", "larva", "larynx", "lash", "lass", "lassitude", "lasso",
    "last", "lasting", "latch", "latchet", "late", "lately", "latent",
    "lateral", "lath", "lathe", "lather", "latin", "latitude", "latter",
    "lattice", "laud", "laudable", "laudanum", "laugh", "laughable",
    "laughter", "launch", "laundress", "laundry", "laurel", "lava",
    "lavatory", "lavender", "lavish", "law", "lawful", "lawn", "lawsuit",
    "lawyer", "lax", "laxative", "lay", "layer", "layman", "lazar",
    "lazy", "lead", "leaden", "leader", "leaf", "leaflet", "leafy",
    "league", "leak", "leakage", "leaky", "lean", "lean", "leap",
    "leapfrog", "learn", "learned", "learner", "lease", "leash", "least",
    "leather", "leave", "leaven", "leaves", "leavings", "lecture", "ledge",
    "ledger", "lee", "leech", "leek", "leer", "lees", "left",
    "leg", "legacy", "legal", "legalize", "legend", "legendary", "legible",
    "legion", "legislate", "legislature", "legitimate", "leisure", "leisurely",
    "lemon", "lemonade", "lend", "lender", "length", "lengthen", "lengthy",
    "lenient", "lens", "lent", "lentil", "leopard", "leper", "leprosy",
    "less", "lessee", "lessen", "lesson", "lest", "let", "lethargy",
    "letter", "lettuce", "level", "lever", "leveret", "levy", "lewd",
    "lexicon", "liability", "liable", "liar", "libation", "libel",
    "liberal", "liberality", "liberate", "liberty", "library", "license",
    "licentiate", "licentious", "lichen", "lick", "lid", "lie", "lie",
    "lieu", "lieutenant", "life", "lifeboat", "lifeguard", "lifeless",
    "lifelong", "lifetime", "lift", "ligament", "ligature", "light",
    "lighten", "lighter", "lighthouse", "lightly", "lightning", "lights",
    "likable", "like", "likelihood", "likely", "liken", "likeness",
    "likewise", "liking", "lilac", "lily", "limb", "lime", "limelight",
    "limestone", "limit", "limitless", "limn", "limp", "limp", "limpid",
    "line", "lineage", "lineal", "lineament", "linear", "linen", "liner",
    "linger", "linguist", "liniment", "lining", "link", "linnet", "linseed",
    "lint", "lion", "lioness", "lip", "liquefy", "liquid", "liquidate",
    "liquor", "liquorice", "lisp", "list", "listen", "listener", "listless",
    "lists", "litany", "literal", "literary", "literature", "lithe",
    "lithography", "litigant", "litigation", "litigious", "litmus", "litter",
    "little", "live", "livelihood", "lively", "liver", "livery", "livid",
    "living", "lizard", "llama", "load", "loadstone", "loaf", "loaf",
    "loam", "loamy", "loan", "loath", "loathe", "loathsome", "loaves",
    "lobby", "lobster", "local", "locality", "localize", "locate", "lock",
    "locker", "locket", "locksmith", "locomotive", "locust", "lodge",
    "lodger", "lodging", "loft", "lofty", "log", "loggerhead", "logic",
    "logical", "loin", "loiter", "loll", "lone", "lonely", "lonesome",
    "long", "longevity", "longitude", "longshoreman", "look", "looking-glass",
    "loom", "loom", "loon", "loop", "loophole", "loose", "loosen",
    "loot", "lop", "quack", "quadrant", "quadrilateral", "quadruped",
    "quadruple", "quaff", "quagmire", "quail", "quail", "quaint", "quake",
    "quaker", "qualification", "qualify", "quality", "qualm", "quantity",
    "quarantine", "quarrel", "quarrelsome", "quarry", "quarry", "quart",
    "quarter", "quarterdeck", "quartermaster", "quarters", "quartet",
    "quartz", "quash", "quaver", "quay", "queen", "queer", "quell",
    "quench", "query", "quest", "question", "questionable", "queue",
    "quibble", "quick", "quicken", "quicklime", "quickly", "quicksand",
    "quicksilver", "quiet", "quietly", "quietude", "quill", "quilt",
    "quince", "quinine", "quinsy", "quintessence", "quire", "quirk",
    "quit", "quite", "quiver", "quiver", "quixotic", "quiz", "quorum",
    "quota", "quotation", "quote", "quoth", "quotient", "rabbi", "rabbit",
    "rabble", "rabid", "race", "racehorse", "racer", "rack", "racket",
    "racy", "radiance", "radiant", "radiate", "radical", "radish",
    "radius", "raffia", "raffle", "raft", "rafter", "rag", "rage",
    "ragged", "raid", "rail", "railway", "raiment", "rain", "rainbow",
    "rainwater", "rainy", "raise", "raisin", "rake", "rally", "ram",
    "ramble", "ramification", "ramify", "ramp", "rampart", "rancid",
    "rancor", "rancour", "random", "range", "ranger", "rank", "rank",
    "rankle", "ransack", "ransom", "rant", "rap", "rapacious", "rapacity",
    "rape", "rapid", "rapidity", "rapier", "rapine", "rapt", "rapture",
    "rapturous", "rare", "rarefy", "rarely", "rarity", "rascal", "rash",
    "rash", "rasher", "rashness", "rasp", "raspberry", "rat", "rate",
    "rather", "ratification", "ratify", "ratio", "ratiocination", "ration",
    "rational", "rationalism", "rattle", "rattlesnake", "ravage", "rave",
    "ravel", "raven", "raven", "ravenous", "ravine", "ravish", "raw",
    "ray", "raze", "razor", "reach", "react", "reaction", "read",
    "reader", "readily", "readiness", "reading", "ready", "real",
    "realism", "realist", "reality", "realize", "really", "realm",
    "reap", "reaper", "reappear", "rear", "rear", "reason", "reasonable",
    "reassure", "rebate", "rebel", "rebellion", "rebellious", "rebound",
    "rebuff", "rebuild", "rebuke", "rebut", "recalcitrant", "recall",
    "recant", "recapitulate", "recede", "receipt", "receive", "receiver",
    "recent", "recently", "receptacle", "reception", "recess", "recession",
    "recipe", "recipient", "reciprocal", "reciprocate", "reciprocity",
    "recital", "recitation", "recite", "reckless", "reckon", "reclaim",
    "reclamation", "recline", "recluse", "recognize", "recoil", "recollect",
    "recollection", "recommend", "recompense", "reconcile", "recondite",
    "reconnaissance", "reconnoitre", "record", "recorder", "recount",
    "recount", "recoup", "recourse", "recover", "recovery", "recreant",
    "recreation", "recrimination", "recruit", "rectangle", "rectify",
    "rectitude", "rector", "rectory", "recumbent", "recuperate", "recur",
    "recurrence", "red", "redbreast", "redden", "reddish", "redeem",
    "redeemer", "redemption", "redolent", "redouble", "redoubt",
    "redoubtable", "redound", "redress", "reduce", "reduction", "redundant",
    "reduplicate", "reed", "reef", "reef", "reek", "reel", "reel",
    "re-establish", "refectory", "refer", "referee", "reference", "refine",
    "refinement", "refinery", "reflect", "reflection", "reflector", "reflex",
    "reflexive", "reform", "reformat", "reformer", "refract", "refraction",
    "refractory", "refrain", "refrain", "refresh", "refreshment",
    "refrigerate", "refrigerator", "refuge", "refugee", "refund", "refusal",
    "refuse", "refuse", "refute", "regal", "regale", "regard", "regard",
    "regardless", "regatta", "regenerate", "regent", "regicide", "regime",
    "regiment", "regimental", "region", "register", "registrar", "registration",
    "registry", "regret", "regretful", "regular", "regularity", "regulate",
    "regulation", "regulator", "rehabilitate", "rehearse", "reign",
    "reimburse", "rein", "reindeer", "reinforce", "reinforcement",
    "restate", "reiterate", "reject", "rejoice", "rejoin", "rejoinder",
    "rejuvenate", "relapse", "relate", "relation", "relationship", "relative",
    "relax", "relaxation", "relay", "release", "relegate", "relent",
    "relentless", "relevant", "reliable", "reliance", "relic", "relict",
    "relief", "relieve", "religion", "religious", "relinquish", "reliquary",
    "relish", "reluctance", "reluctant", "rely", "remain", "remainder",
    "remains", "remand", "remark", "remarkable", "remedy", "remember",
    "remembrance", "remind", "reminiscence", "remiss", "remission", "remit",
    "remittance", "remnant", "remodel", "remonstrance", "remonstrate",
    "remorse", "remorseful", "remorseless", "remote", "remount", "remove",
    "remunerate", "remuneration", "rencounter", "rend", "render", "rendezvous",
    "renegade", "renew", "renewal", "rennet", "renounce", "renovate",
    "renown", "renowned", "rent", "rent", "renunciation", "reopen",
    "reorganize", "repair", "repairer", "reparable", "reparation",
    "repartee", "repast", "repatriate", "repay", "repeal", "repeat",
    "repeatedly", "repel", "repent", "repentance", "repentant", "repercussion",
    "repertory", "repetition", "repine", "replace", "replenish", "replevin",
    "replica", "reply", "report", "reporter", "repose", "repose",
    "repository", "reprehend", "reprehensible", "represent", "representation",
    "representative", "repress", "repression", "reprieve", "reprimand",
    "reprisal", "reproach", "reproachful", "reprobate", "reproduce",
    "reproduction", "reproof", "reprove", "reptile", "republic", "republican",
    "repudiate", "repugnance", "repugnant", "repulse", "repulsion",
    "repulsive", "reputable", "reputation", "repute", "request", "requiem",
    "require", "requirement", "requisite", "requisition", "requital",
    "requite", "rescind", "rescript", "rescue", "research", "resemblance",
    "resemble", "resent", "resentful", "resentment", "reservation",
    "reserve", "reserved", "reservoir", "reside", "residence", "resident",
    "residential", "residue", "resign", "resignation", "resilient",
    "resin", "resinous", "resist", "resistance", "resolute", "resolution",
    "resolve", "resonance", "resonant", "resort", "resound", "resource",
    "respect", "respectable", "respectful", "respective", "respire",
    "respite", "resplendent", "respond", "respondent", "response",
    "responsibility", "responsible", "responsive", "rest", "rest",
    "restaurant", "restitution", "restless", "restoration", "restorative",
    "restore", "restrain", "restraint", "restrict", "restriction", "result",
    "resume", "resurrection", "resuscitate", "retail", "retain", "retainer",
    "retaliate", "retaliation", "retard", "retch", "retention", "retentive",
    "reticent", "retinue", "retire", "retirement", "retort", "retort",
    "retouch", "retrace", "retract", "retreat", "retrench", "retribution",
    "retrieve", "retriever", "retrograde", "retrospect", "retrospective",
    "return", "reunion", "reunite", "reveal", "reveille", "revel",
    "revelation", "revenge", "revengeful", "revenue", "reverberate",
    "revere", "reverence", "reverend", "reverent", "reverie", "reversal",
    "reverse", "reversion", "revert", "review", "revile", "revise",
    "revision", "revival", "revive", "revocation", "revoke", "revolt",
    "revolting", "revolution", "revolutionary", "revolutionist", "revolve",
    "revolver", "revulsion", "reward", "rhapsody", "rhenish", "rhetoric",
    "rhetorical", "rheumatism", "rhinoceros", "rhododendron", "rhubarb",
    "rhyme", "rhythm", "rib", "ribald", "ribbon", "rice", "rich",
    "riches", "richly", "rick", "rickets", "rid", "riddance", "ridden",
    "riddle", "ride", "rider", "ridge", "ridicule", "ridiculous", "rife",
    "riffraff", "rifle", "rifleman", "rift", "rig", "rigging", "right",
    "righteous", "rightful", "rigid", "rigidity", "rigmarole", "rigor",
    "rigorous", "rill", "rim", "rime", "rind", "ring", "ring",
    "ringdove", "ringleader", "ringlet", "ringworm", "rink", "rinse",
    "riot", "riotous", "rip", "ripe", "ripen", "ripple", "rise",
    "risible", "rising", "risk", "risky", "rite", "ritual", "rival",
    "rivalry", "river", "rivet", "rivulet", "roach", "road", "roadstead",
    "roadway", "roam", "roan", "roar", "roast", "rob", "robber",
    "robbery", "robe", "robin", "robust", "roc", "rock", "rock",
    "rocket", "rocky", "rod", "rode", "rodent", "roe", "roe",
    "rogue", "roguery", "roguish", "roister", "role", "roll", "roller",
    "romance", "romantic", "romp", "rood", "roof", "rook", "rook",
    "room", "roomy", "roost", "rooster", "root", "root", "rope",
    "rosary", "rose", "rosebud", "rosemary", "rosette", "rosewood",
    "rosin", "roster", "rostrum", "rosy", "rot", "rotary", "rotate",
    "rotation", "roten", "rotifer", "rotund", "rotunda", "rouble",
    "rouge", "rough", "roughen", "roughly", "roughneck", "roulette",
    "round", "roundabout", "roundelay", "roundly", "rounds", "rouse",
    "rout", "rout", "route", "routine", "rove", "rover", "row",
    "row", "row", "rowdy", "rowel", "royal", "royalist", "royalty",
    "rub", "rubber", "rubbish", "rubble", "rubric", "ruby", "rudder",
    "ruddy", "rude", "rudiment", "rudimentary", "rue", "rueful",
    "ruff", "ruffian", "ruffle", "rug", "rugged", "ruin", "ruinous",
    "rule", "ruler", "rum", "rumble", "ruminate", "rummage", "rumor",
    "rumour", "rump", "rumple", "run", "runaway", "rung", "rung",
    "runner", "runway", "rupture", "rural", "rush", "rush", "russet",
    "russian", "rust", "rustic", "rusticity", "rustle", "rusty",
    "rut", "rye", "sable", "sabot", "sabotage", "sabre", "saccharin",
    "sachel", "sack", "sack", "sackbut", "sackcloth", "sacrament",
    "sacred", "sacrifice", "sacrilege", "sacrilegious", "sacristan",
    "sacristy", "sad", "sadden", "saddle", "saddler", "sadly", "sadness",
    "safe", "safe-conduct", "safeguard", "safely", "safety", "saffron",
    "sag", "sagacious", "sagacity", "sage", "sage", "sago",
    "said", "sail", "sailing-vessel", "sailor", "saint", "saintly",
    "sake", "salad", "salamander", "salary", "sale", "saleable",
    "salesman", "salient", "saline", "saliva", "sallow", "sally",
    "salmon", "saloon", "salt", "saltcellar", "saltpetre", "salty",
    "salubrious", "salutary", "salutation", "salute", "salvage", "salvation",
    "salve", "salver", "salvo", "same", "sameness", "samphire", "sample",
    "sanatorium", "sanctify", "sanctimonious", "sanction", "sanctity",
    "sanctuary", "sand", "sandal", "sandalwood", "sandbag", "sandpiper",
    "sandstone", "sandwich", "sandy", "sane", "sanguine", "sanitary",
    "sanity", "sanscrit", "sap", "sap", "sapient", "sapling", "sapphire",
    "sarcasm", "sarcastic", "sarcophagus", "sardine", "sardonic",
    "sarsaparilla", "sash", "sash", "satan", "satanic", "satchel",
    "sate", "satellite", "satiate", "satiety", "satin", "satire",
    "satirical", "satirist", "satirize", "satisfaction", "satisfactory",
    "satisfy", "saturate", "saturn", "saturnalia", "saturnine", "satyr",
    "sauce", "saucepan", "saucer", "saucy", "saunter", "sausage",
    "savage", "savagery", "savannah", "savant", "save", "save",
    "saveloy", "saving", "savings", "saviour", "savour", "savoury",
    "saw", "saw", "sawdust", "sawyer", "saxifrage", "saxon",
    "say", "saying", "scab", "scabbard", "scaffold", "scaffolding",
    "scald", "scale", "scale", "scallop", "scalp", "scaly",
    "scamp", "scamper", "scan", "scandal", "scandalize", "scandalous",
    "scant", "scanty", "scapegoat", "scar", "scarab", "scarce",
    "scarcely", "scarcity", "scare", "scarecrow", "scarf", "scarf",
    "scarlet", "scathe", "scathless", "scatter", "scavenger", "scene",
    "scenery", "scenic", "scent", "sceptic", "sceptical", "scepticism",
    "sceptre", "schedule", "scheme", "schemer", "schism", "schismatic",
    "scholar", "scholastic", "school", "schoolboy", "schoolmaster",
    "schooner", "sciatica", "science", "scientific", "scientist",
    "scimitar", "scintilla", "scintillate", "scion", "scissors", "scoff",
    "scold", "sconce", "scoop", "scope", "scorch", "score",
    "scorn", "scornful", "scorpion", "scotch", "scot-free", "scoundrel",
    "scour", "scourge", "scout", "scout", "scowl", "scrag",
    "scraggy", "scramble", "scrap", "scrape", "scraper", "scratch",
    "scrawl", "scream", "screech", "screech-owl", "screen", "screw",
    "screw-driver", "screw-propeller", "scribble", "scribe", "scrimmage",
    "scrip", "scrip", "script", "scripture", "scrivener", "scrofula",
    "scroll", "scrub", "scruple", "scrupulous", "scrutinize", "scrutiny",
    "scud", "scuffle", "scull", "scullery", "scullion", "sculptor",
    "sculpture", "scum", "scupper", "scurf", "scurrilous", "scurry",
    "scurvy", "scurvy", "scutcheon", "scythe", "sea", "seaboard",
    "sea-breeze", "seacoast", "seafaring", "seagull", "seal", "seal",
    "sealing-wax", "seaman", "seamstress", "seaport", "sear", "search",
    "search-warrant", "seascape", "shore", "season", "seasonable",
    "seasoning", "seat", "seaward", "seaweed", "secede", "secession",
    "exclude", "second", "second", "secondary", "secrecy", "secret",
    "secretary", "secrete", "secretion", "secretive", "sect", "sectarian",
    "section", "sector", "secular", "secure", "securely", "security",
    "sedan", "sedate", "sedative", "sedentary", "sedge", "sediment",
    "sedition", "seditious", "seduce", "seduction", "sedulous", "see",
    "see", "seed", "seedling", "seedy", "seek", "seem", "seeming",
    "seemly", "seen", "seep", "seer", "seesaw", "seethe",
    "segment", "segregate", "seignior", "seine", "seismometer", "seize",
    "seizure", "seldom", "select", "selection", "selenium", "self",
    "selfish", "selfsame", "sell", "seller", "selvedge", "semaphore",
    "semblance", "semicolon", "seminal", "seminary", "semitic", "senate",
    "senator", "send", "sender", "seneschal", "senile", "senior",
    "seniority", "senna", "sensation", "sensational", "sense", "senseless",
    "sensibility", "sensible", "sensitive", "sensory", "sensual",
    "sensuality", "sentence", "sententious", "sentient", "sentiment",
    "sentimental", "sentinel", "sentry", "sepal", "separable", "separate",
    "separation", "sepia", "sepoy", "september", "septic", "septuagesimal",
    "sepulchre", "sepulchral", "sequel", "sequence", "sequester",
    "sequestrate", "seraph", "seraphic", "serenade", "serene", "serenity",
    "serf", "serfdom", "serge", "sergeant", "serial", "series",
    "serious", "sermon", "serpent", "serpentine", "serrated", "serum",
    "servant", "serve", "server", "service", "serviceable", "servile",
    "servility", "servitude", "sesame", "session", "set", "seton",
    "settle", "settlement", "settler", "seven", "seventeen", "seventy",
    "sever", "several", "severe", "severely", "severity", "sew",
    "sewer", "sewerage", "sex", "sexton", "shabby", "shackle",
    "shad", "shade", "shadow", "shadowy", "shady", "shaft",
    "shag", "shaggy", "shah", "shake", "shaky", "shale",
    "shall", "shallop", "shallot", "shallow", "sham", "shambles",
    "shame", "shamefaced", "shameful", "shameless", "shammy", "shampoo",
    "shamrock", "shank", "shanty", "shape", "shapeless", "shapely",
    "share", "shareholder", "shark", "sharp", "sharpen", "sharper",
    "sharply", "shatter", "shave", "shaver", "shawl", "she",
    "sheaf", "shear", "shears", "sheath", "sheathe", "sheave",
    "shed", "shed", "sheen", "sheep", "sheepfold", "sheepskin",
    "sheer", "sheet", "sheet-lightning", "sheik", "shekel", "shelf",
    "shell", "shellac", "shelter", "shelve", "shepherd", "sherbet",
    "sheriff", "sherry", "shew", "shield", "shift", "shiftless",
    "shifty", "shillelagh", "shilling", "shimmer", "shin", "shine",
    "shingle", "shingles", "shiny", "ship", "shipment", "shipwreck",
    "shipwright", "shire", "shirk", "shirt", "shiver", "shiver",
    "shoal", "shoal", "shock", "shock", "shod", "shoddy",
    "shoe", "shoemaker", "shone", "shook", "shoot", "shop",
    "shopkeeper", "shore", "shore", "shorn", "short", "shortbread",
    "shortcake", "shortcoming", "shorten", "shorthand", "shortly", "shorts",
    "shot", "shot", "should", "shoulder", "shout", "shove",
    "shovel", "show", "shower", "showery", "shown", "showy",
    "shrank", "shrapnel", "shred", "shrew", "shrewd", "shrewish",
    "shriek", "shrift", "shrill", "shrimp", "shrine", "shrink",
    "shrinkage", "shrive", "shrivel", "shroud", "shrove-tide", "shrub",
    "shrubbery", "shrug", "shrunk", "shrunken", "shudder", "shuffle",
    "shun", "shunt", "shut", "shutter", "shuttle", "shuttlecock",
    "shy", "shy", "siberian", "sibilant", "sibyl", "sick",
    "sicken", "sickle", "sickly", "sickness", "side", "sideboard",
    "sidelong", "sidereal", "sidesaddle", "sideways", "sidle", "siege",
    "siesta", "sieve", "sift", "sigh", "sight", "sign",
    "signal", "signalize", "signature", "signet", "significance", "significant",
    "signify", "signpost", "silence", "silent", "silhouette", "silica",
    "silicon", "silk", "silkworm", "silky", "sill", "silly",
    "silt", "silver", "silversmith", "silvery", "similar", "similarity",
    "simile", "similitude", "simmer", "simony", "simoom", "simper",
    "simple", "simpleton", "simplicity", "simplify", "simply", "simulate",
    "simultaneous", "sin", "since", "sincere", "sincerity", "sinecure",
    "sinew", "sinewy", "sinful", "sing", "singe", "singer",
    "single", "single-stick", "singly", "singular", "singularity", "sinister",
    "sink", "sinner", "sinuous", "sip", "siphon", "sir",
    "sire", "siren", "sirloin", "sirocco", "sister", "sisterhood",
    "sit", "site", "sitting", "situation", "six", "sixteen",
    "sixty", "size", "size", "skate", "skate", "skein",
    "skeleton", "sceptic", "sketch", "sketchbook", "sketchy", "skew",
    "skewer", "skiff", "skilful", "skill", "skillet", "skim",
    "skimmer", "skin", "skinflint", "skinny", "skip", "skip",
    "skipper", "skirmish", "skirt", "skit", "skittles", "skulk",
    "skull", "skullcap", "skunk", "sky", "skylark", "skylight",
    "sky-rocket", "slab", "slack", "slacken", "slag", "slain",
    "slake", "slam", "slander", "slanderous", "slang", "slant",
    "slap", "slash", "slate", "slater", "slattern", "slaughter",
    "slave", "slaver", "slavery", "slavish", "slay", "slayer",
    "sledge", "sledge-hammer", "sleek", "sleep", "sleeper", "sleepy",
    "sleet", "sleeve", "sleigh", "sleight", "slender", "slept",
    "slice", "slick", "slide", "slight", "slight", "slightly",
    "slim", "slime", "slimy", "sling", "sling", "slink",
    "slip", "slipknot", "slipper", "slippery", "slit", "sloe",
    "sloop", "slop", "slope", "sloppy", "slot", "sloth",
    "slothful", "slouch", "slough", "slough", "sloven", "slovenly",
    "slow", "slowworm", "sludge", "slue", "slug", "sluggard",
    "sluggish", "sluice", "slum", "slumber", "slump", "slung",
    "slunk", "slur", "slush", "slushy", "sly", "smack",
    "smack", "smack", "small", "smallpox", "smart", "smash",
    "smatter", "smattering", "smear", "smell", "smelt", "smelt",
    "smile", "smirk", "smite", "smith", "smithy", "smock",
    "smoke", "smoker", "smoky", "smooth", "smote", "smother",
    "smoulder", "smug", "smuggle", "smut", "smutty", "snail",
    "snake", "snap", "snapdragon", "snappish", "snare", "snarl",
    "snarl", "snatch", "sneak", "sneer", "sneeze", "sniff",
    "snip", "snipe", "snivel", "snob", "snobbish", "snooze",
    "snore", "snort", "snout", "snow", "snowdrop", "snowy",
    "snub", "snuff", "snuffers", "snuffle", "snug", "snuggle",
    "so", "soak", "soap", "soapy", "soar", "sob",
    "sober", "sobriety", "sobriquet", "sociable", "social", "socialism",
    "society", "sock", "socket", "soda", "sodden", "sodium",
    "sofa", "soft", "soften", "softly", "soil", "soil",
    "sojourn", "solace", "solar", "sold", "solder", "soldier",
    "sole", "sole", "sole", "solemn", "solemnize", "solemnity",
    "solicit", "solicitor", "solicitous", "solitude", "solitude", "solo",
    "solomon", "solstice", "soluble", "solution", "solve", "solvent",
    "sombre", "some", "somebody", "somehow", "something", "sometime",
    "sometimes", "somewhat", "somewhere", "somnambulist", "somniferous",
    "somnolent", "son", "sonata", "song", "songster", "sonnet",
    "sonorous", "soon", "soot", "sooth", "soothe", "soothsayer",
    "sooty", "sop", "sophism", "sophist", "sophisticate", "sophistry",
    "soporific", "soprano", "sorcerer", "sorcery", "sordid", "sore",
    "sorely", "sorrel", "sorrel", "sorrow", "sorrowful", "sorry",
    "sort", "sortie", "sot", "sottish", "soul", "sound",
    "sound", "sound", "sound", "soup", "sour", "source",
    "house", "hovel", "hover", "how", "howitzer", "howl",
    "hub", "huckleberry", "huddle", "hue", "huff", "hug",
    "huge", "hulk", "hull", "hum", "human", "humane",
    "humanist", "humanity", "humble", "humbug", "humdrum", "humid",
    "humidity", "humiliate", "humiliation", "humility", "hummingbird", "humor",
    "humorous", "humour", "hump", "humpback", "humus", "hunch",
    "hunchback", "hundred", "hung", "hunger", "hungry", "hunt",
    "hunter", "huntsman", "hurdle", "hurl", "hurricane", "hurry",
    "hurt", "hurtful", "husband", "husbandry", "hush", "husk",
    "husky", "hussar", "hustle", "hut", "hyacinth", "hybrid",
    "hydra", "hydrangea", "hydrant", "hydraulic", "hydrogen", "hydrophobia",
    "hyena", "hygiene", "hygrometer", "hymn", "hyperbola", "hyphen",
    "hypochondria", "hypocrisy", "hypocrite", "hypotenuse", "hypothesis",
    "hyssop", "hysteria", "hysterical", "iambic", "ibex", "ibis",
    "ice", "iceberg", "ichneumon", "icicle", "icy", "idea",
    "ideal", "idealist", "idealize", "identical", "identify", "identity",
    "idiom", "idiomatic", "idiot", "idiotic", "idle", "idler",
    "idly", "idol", "idolatry", "idolize", "idyll", "if",
    "igneous", "ignite", "ignoble", "ignominious", "ignominy", "ignorance",
    "ignorant", "ignore", "ill", "illegal", "illegible", "illegitimate",
    "illicit", "illiterate", "illness", "illuminate", "illusion", "illusory",
    "illustrate", "illustration", "illustrious", "image", "imagery", "imaginary",
    "imagination", "imagine", "imbecile", "imbue", "imitate", "imitation",
    "immaculate", "immanent", "immaterial", "immature", "immeasurable", "immediate",
    "immemorial", "immense", "immensity", "immerse", "immigrant", "immigrate",
    "imminent", "immobile", "immoderate", "immodest", "immolate", "immoral",
    "immortal", "immortality", "immovable", "immunity", "immunize", "immure",
    "immutable", "imp", "impact", "impair", "impale", "impalpable",
    "impart", "impartial", "impassable", "impassioned", "impassive", "impatience",
    "impatient", "impeach", "impeccable", "impede", "impediment", "impel",
    "impend", "impenitent", "imperative", "imperceptible", "imperfect", "imperial",
    "imperialism", "imperious", "imperishable", "impersonate", "impertinent", "impervious",
    "impetuous", "impetus", "impiety", "impinge", "impious", "implacable",
    "implant", "implement", "implicate", "implicit", "implore", "imply",
    "impolite", "impolitic", "import", "importance", "important", "importunate",
    "importune", "impose", "imposing", "impossible", "impostor", "imposture",
    "impotent", "impound", "impoverish", "impracticable", "imprecation", "impregnable",
    "impregnate", "impress", "impression", "impressive", "imprint", "imprison",
    "improbable", "impromptu", "improper", "impropriety", "improve", "improvement",
    "improvident", "improvise", "imprudent", "impudent", "impugn", "impulse",
    "impulsive", "impunity", "impure", "impurity", "imput", "tabby",
    "table", "tableau", "tableland", "tablet", "taboo", "tabular",
    "tacit", "taciturn", "tack", "tackle", "tact", "tactics",
    "tadpole", "taffeta", "tag", "tail", "tailor", "taint",
    "take", "tale", "talent", "talisman", "talk", "talkative",
    "tall", "tallow", "tally", "talon", "tamarind", "tambour",
    "tambourine", "tame", "tamper", "tan", "tandem", "tangent",
    "tangerine", "tangible", "tangle", "tank", "tankard", "tanner",
    "tannery", "tantalize", "tantamount", "tap", "tape", "taper",
    "tapestry", "tapioca", "tapir", "tapster", "tar", "tardy",
    "tare", "target", "tariff", "tarn", "tarnish", "tarpaulin",
    "tarry", "tart", "tart", "tartan", "tartar", "task",
    "tassel", "taste", "tasteful", "tasteless", "tasty", "tatter",
    "tattle", "tattoo", "taunt", "taurus", "taut", "tautology",
    "tavern", "tawny", "tax", "taxable", "taxation", "tea",
    "teach", "teacher", "teak", "teal", "team", "teamster",
    "tear", "tear", "tease", "teasel", "teat", "technical",
    "technics", "technology", "tedious", "tedium", "teem", "teens",
    "teeth", "teetotaler", "telegram", "telegraph", "telephone", "telescope",
    "tell", "teller", "temerity", "temper", "temperament", "temperance",
    "temperate", "tempest", "tempestuous", "temple", "temple", "temporal",
    "temporary", "temporize", "tempt", "temptation", "ten", "tenable",
    "tenacious", "tenacity", "tenant", "tench", "tend", "tend",
    "tendency", "tender", "tender", "tender", "tendon", "tendril",
    "tenement", "tenet", "tenfold", "tennis", "tenon", "tenor",
    "tense", "tense", "tension", "tent", "tentacle", "tentative",
    "tenter", "tenth", "tenuity", "tenuous", "tenure", "tepid",
    "term", "termagant", "terminate", "termination", "terminus", "termite",
    "tern", "terrace", "terracotta", "terra-firma", "terrapin", "terrestrial",
    "terrible", "terrier", "terrific", "terrify", "territory", "terror",
    "terrorism", "terse", "tertian", "tesselate", "test", "testaceous",
    "testament", "testator", "tester", "testify", "testimonial", "testimony",
    "testy", "tetanus", "tether", "tetrarch", "teutonic", "text",
    "textbook", "textile", "texture", "than", "thank", "thankful",
    "thanks", "thanksgiving", "that", "thatch", "thaw", "the",
    "theatre", "theatrical", "theban", "theft", "their", "theism",
    "them", "theme", "theocracy", "theology", "theorem", "theory",
    "therapeutic", "there", "thereabout", "thereafter", "thereby", "therefor",
    "therefore", "therein", "thereof", "thereon", "thereto", "thereupon",
    "therewith", "thermometer", "these", "thesis", "thew", "they",
    "thick", "thicken", "thicket", "thickness", "thief", "thieve",
    "thievish", "thigh", "thimble", "thin", "thine", "thing",
    "think", "third", "thirst", "thirsty", "thirteen", "thirty",
    "this", "thistle", "thither", "thole", "thong", "thorax",
    "thorn", "thorny", "thorough", "thoroughbred", "thoroughfare", "thoroughly",
    "those", "thou", "though", "thought", "thoughtful", "thoughtless",
    "thousand", "thrall", "thraldom", "thrash", "thread", "threadbare",
    "threat", "threaten", "three", "threefold", "threshold", "threw",
    "thrice", "thrift", "thrifty", "thrill", "thrive", "throat",
    "throb", "throe", "throne", "throng", "throstle", "throttle",
    "through", "throughout", "throw", "thrum", "thrush", "thrush",
    "thrust", "thud", "thug", "thumb", "thump", "thunder",
    "thunderbolt", "thunderstorm", "thursday", "thus", "thwack", "thwart",
    "thy", "thyme", "tiara", "tibia", "tic", "tick",
    "tick", "ticket", "tickle", "ticklish", "tidal", "tide",
    "tidings", "tidy", "tie", "tier", "tiff", "tiffin",
    "tiger", "tigress", "tight", "tighten", "tights", "tile",
    "till", "till", "tillage", "tiller", "tiller", "tilt",
    "tilt", "timber", "timbre", "timbrel", "time", "timepiece",
    "timely", "timid", "timidity", "timorous", "tin", "tincture",
    "tinder", "tine", "tinfoil", "tinge", "tingle", "tinker",
    "tinkle", "tinsel", "tint", "tiny", "tip", "tip",
    "tippet", "tipple", "tippler", "tipsy", "tiptoe", "tirade",
    "tire", "tire", "tired", "tiresome", "tissue", "tit",
    "titanic", "tithe", "titillate", "title", "titled", "titmouse",
    "titter", "tittle", "titular", "to", "toad", "toadstool",
    "toast", "toast", "tobacco", "toboggan", "tocsin", "today",
    "toddle", "toe", "toffee", "toga", "together", "toil",
    "toilet", "toilsome", "token", "told", "tolerable", "tolerance",
    "tolerant", "tolerate", "toleration", "toll", "toll", "tollgate",
    "tomahawk", "tomato", "tomb", "tomboy", "tombstone", "tomcat",
    "tome", "tomorrow", "tomtit", "ton", "tone", "tongs",
    "tongue", "tonic", "tonnage", "tonsil", "tonsorial", "too",
    "tool", "tooth", "toothache", "top", "topaz", "tope",
    "toper", "topic", "topography", "topping", "topple", "top-sail",
    "topsy-turvy", "torch", "tore", "torment", "torment", "tornado",
    "torpedo", "torpid", "torpidity", "torpor", "torrent", "torrid",
    "torsion", "torso", "tortoise", "tortuous", "torture", "tory",
    "toss", "total", "totem", "totter", "toucan", "touch",
    "touching", "touchstone", "touchwood", "tough", "toughen", "tour",
    "tourist", "tournament", "tourney", "tout", "tow", "tow",
    "toward", "towards", "towel", "tower", "towering", "town",
    "township", "toxicology", "toy", "trace", "trace", "tracer",
    "tracery", "trachea", "track", "trackless", "tract", "tract",
    "tractable", "traction", "trade", "trader", "tradesman", "trades-union",
    "tradition", "traditional", "tradduce", "traffic", "tragedian", "tragedy",
    "tragic", "trail", "train", "train", "trainer", "train-oil",
    "trait", "traitor", "traitorous", "trajectory", "tram", "trammel",
    "tramp", "trample", "tramway", "trance", "tranquil", "tranquility",
    "transact", "transaction", "transcend", "transcendent", "transcendental", "transcribe",
    "transcript", "transcription", "transfer", "transfer", "transfigure", "transfix",
    "transform", "transformation", "transfuse", "transfusion", "transgress", "transgression",
    "transgressive", "transient", "transit", "transition", "transitive", "transitory",
    "translate", "translation", "translator", "translucent", "transmigrate", "transmission",
    "transmit", "transmutable", "transmute", "transom", "transparent", "transpire",
    "transplant", "transport", "transport", "transportation", "transpose", "transposition",
    "transubstantiation", "transverse", "trap", "trap", "trap-door", "trapeze",
    "trapper", "trappings", "trash", "trashy", "travail", "travel",
    "traveler", "traverse", "travesty", "trawl", "trawler", "tray",
    "treachrous", "treachery", "treacle", "tread", "treadle", "treadmill",
    "treason", "treasonable", "treasure", "treasurer", "treasury", "treat",
    "treatise", "treatment", "treaty", "treble", "treble", "tree",
    "trefoil", "trellis", "tremble", "tremendous", "tremor", "tremulous",
    "trench", "trenchant", "trencher", "trepan", "trepidation", "trespass",
    "tress", "trestle", "triad", "trial", "triangle", "triangular",
    "tribe", "tribulation", "tribunal", "tribune", "tributary", "tribute",
    "trice", "trick", "trickery", "trickle", "trickster", "tricky",
    "tricolor", "tricycle", "trident", "tried", "triennial", "trifle",
    "trifling", "trigger", "trigonometry", "trill", "trillion", "trim",
    "trimming", "trinity", "trinket", "trio", "trip", "tripartite",
    "tripe", "triple", "triplicate", "tripod", "triptych", "trireme",
    "trisect", "trite", "triturate", "triumph", "triumphal", "triumphant",
    "triumvirate", "trivet", "trivial", "triviality", "trochee", "trod",
    "trodden", "troll", "trolley", "troop", "trooper", "trope",
    "trophy", "tropic", "tropical", "trot", "troth", "troubadour",
    "trouble", "troublesome", "trough", "trounce", "troupe", "trousers",
    "trousseau", "trout", "trowel", "troy-weight", "truant", "truce",
    "truck", "truck", "truckle", "truculent", "trudge", "true",
    "truffle", "truly", "trump", "trump", "trumpery", "trumpet",
    "trumpeter", "truncate", "truncheon", "trundle", "trunk", "trunnion",
    "truss", "truss", "trust", "trustee", "trustful", "trustworthy",
    "trusty", "truth", "truthful", "try", "trying", "tryst",
    "tub", "tube", "tuber", "tubercle", "tuberculosis", "tuberose",
    "tuberous", "tubing", "tubular", "tuck", "tucker", "tuesday",
    "tufa", "tuft", "tug", "tuition", "tulip", "tumble",
    "tumbler", "tumbrel", "tumor", "tumour", "tumult", "tumultuous",
    "tun", "tune", "tuneful", "tunic", "tunnel", "tunny",
    "turban", "turbid", "turbot", "turbulent", "tureen", "turf",
    "turfy", "turgid", "turk", "turkey", "turkish", "turmeric",
    "turmoil", "turn", "turncoat", "turner", "turnery", "turning",
    "turnip", "turnkey", "turnpike", "turnspit", "turnstile", "turpentine",
    "turpitude", "turquoise", "turret", "turtle", "turtledove", "tusk",
    "tussle", "tutelage", "tutelary", "tutor", "twaddle", "twain",
    "twang", "tweak", "tweed", "tweezers", "twelfth", "twelve",
    "twelvemonth", "twenty", "twice", "twig", "twilight", "twill",
    "twin", "twine", "twinge", "twinkle", "twirl", "twist",
    "twit", "twitch", "twitter", "two", "twofold", "tympanum",
    "type", "typewriter", "typhoid", "typhoon", "typhus", "typical",
    "typify", "typography", "tyrannical", "tyrannize", "tyranny", "tyrant",
    "tyro", "udder", "ugly", "ukase", "ulcer", "ulcerate",
    "ulterior", "ultimate", "ultramarine", "ultramontane", "umbel", "umber",
    "umbilical", "umbrage", "umbrageous", "umbrella", "umpire", "un-",
    "unabashed", "unaccented", "unacceptable", "unaccommodating", "unaccompanied", "unaccountable",
    "unaccustomed", "unacknowledged", "unadorned", "unadulterated", "unadvised", "unaffected",
    "unalloyed", "unalterable", "unambiguous", "unamiable", "unanimous", "unanimity",
    "unanswerable", "unappalled", "unappeasable", "unapproachable", "unapt", "unarmed",
    "unasked", "unaspiring", "unassisted", "unassuming", "unattached", "unattainable",
    "unattended", "unauthorized", "unavailable", "unavailing", "unavoidable", "unaware",
    "unawares", "unbacked", "unbar", "unbearable", "unbecoming", "unbelief",
    "unbeliever", "unbend", "unbending", "unbiased", "unbind", "unblushing",
    "unbolt", "unborn", "unbosom", "unbound", "unbounded", "unbridled",
    "unbuckle", "unburden", "unbutton", "uncanny", "unceasing", "unceremonious",
    "uncertain", "uncertainty", "unchain", "uncharitable", "unchaste", "uncivil",
    "uncivilized", "uncle", "unclean", "unclothe", "uncoil", "uncomfortable",
    "uncommon", "uncompromising", "unconcerned", "unconditional", "unconquerable", "unconscious",
    "unconstitutional", "unconstrained", "uncontrollable", "uncontrolled", "unconverted", "uncork",
    "uncouth", "uncovenanted", "uncover", "unction", "unctuous", "uncultivated",
    "undaunted", "undecided", "undefiled", "undemonstrative", "undeniable", "under",
    "undercurrent", "undergo", "undergraduate", "underground", "undergrowth", "underhand",
    "underline", "undermine", "underneath", "underrate", "undersell", "undersign",
    "understand", "understanding", "understrapper", "undertake", "undertaker", "undertaking",
    "undervalue", "underwood", "underwrite", "underwriter", "undeserved", "undesigned",
    "undesirable", "undeviating", "undignified", "undisciplined", "undistinguished", "undivided",
    "undo", "undoing", "undomesticated", "undone", "undoubtedly", "undress",
    "undue", "undulate", "undulation", "unduly", "undutiful", "undying",
    "unearth", "unearthly", "uneasy", "uneducated", "unembarrassed", "unemployed",
    "unending", "unequal", "unequaled", "unequivocal", "unerring", "unessential",
    "uneven", "unexampled", "unexceptionable", "unexpected", "unexpressed", "unfailing",
    "unfair", "unfaithful", "unfaltering", "unfamiliar", "unfashionable", "unfasten",
    "unfathomable", "unfavorable", "unfeasible", "unfeeling", "unfeigned", "unfetter",
    "unfilial", "unfinished", "unfit", "unflagging", "unflinching", "unfold",
    "unforeseen", "unforgiving", "unfortunate", "unfounded", "unfriendly", "unfruitful",
    "unfurl", "unfurnished", "ungainly", "ungenerous", "ungird", "ungodly",
    "ungovernable", "ungraceful", "ungracious", "ungrateful", "ungrounded", "unguarded",
    "unguent", "unhallowed", "unhand", "unhandsome", "unhandy", "unhappy",
    "unharmed", "unharness", "unhealthy", "unheard", "unheeded", "unhinge",
    "unholy", "unhook", "unhorse", "unhurt", "unicorn", "uniform",
    "uniformity", "unify", "unimpeachable", "unimportant", "uninhabitable", "uninhabited",
    "uninitiated", "uninjured", "unintelligible", "unintentional", "uninteresting", "uninterrupted",
    "uninvited", "union", "unique", "unison", "unit", "unitarian",
    "unite", "united", "unity", "universal", "universe", "university",
    "unjust", "unjustifiable", "unkempt", "unkind", "unking", "unknight",
    "unknowingly", "unknown", "unlace", "unlade", "unlatch", "unlawful",
    "unlearn", "unless", "unlettered", "unlike", "unlikely", "unlimited",
    "unlink", "unload", "unlock", "unloose", "unloveliness", "unlovely",
    "unlucky", "unman", "unmanageable", "unmanly", "unmannerly", "unmarried",
    "unmask", "unmeaning", "unmerchantable", "unmerciful", "unmerited", "unmindful",
    "unmistakable", "unmitigated", "unmoved", "unnatural", "unnecessary", "unneighborly",
    "unnerve", "unnoticed", "unnumbered", "unobtrusive", "unoccupied", "unoffending",
    "unofficial", "unorganized", "unpack", "unpaid", "unpalatable", "unparalleled",
    "unpardonable", "unparliamentary", "unpeople", "unpleasant", "unpleasantness", "unpliant",
    "unpolished", "unpolluted", "unpopular", "unprecedented", "unprejudiced", "unpremeditated",
    "unprepared", "unpretending", "unprincipled", "unproductive", "unprofessional", "unprofitable",
    "unpromising", "unpropitious", "unprotected", "unprovoked", "unpublished", "unpunished",
    "unqualified", "unquenchable", "unquestionable", "unravel", "unread", "unready",
    "unreal", "unreasonable", "unreconciled", "unrecorded", "unredeemed", "unreflecting",
    "unregenerate", "unregistered", "unrelenting", "unremitting", "unrepresented", "unrequited",
    "unreserved", "unresisting", "unresolved", "unresponsive", "unrest", "unrestrained",
    "unrestricted", "unriddle", "unrighteous", "unripe", "unrivaled", "unrobe",
    "unroll", "unruffled", "unruly", "unsaddle", "unsafe", "unsaid",
    "unsaleable", "unsanctified", "unsatisfactory", "unsatisfied", "unsavory", "unsay",
    "unscathed", "unschooled", "unscientific", "unscrew", "unscrupulous", "unseal",
    "unsearchable", "unseasonable", "unseat", "unsectarian", "unseemly", "unseen",
    "unselfish", "unserviceable", "unsettle", "unsettled", "unshackle", "unshaken",
    "unsheathe", "unship", "unshod", "unshorn", "unsightly", "unskilful",
    "unsociable", "unsoiled", "unsold", "unsoldierly", "unsolicited", "unsophisticated",
    "unsound", "unsparing", "unspeakable", "unspotted", "unstable", "unstained",
    "unstudied", "unsubmissive", "unsubstantiated", "unsuccessful", "unsuitable", "unsuited",
    "unsullied", "unsung", "unsurpassed", "unsuspected", "unsuspicious", "unswerving",
    "unsymmetrical", "untamable", "untamed", "untaught", "untenable", "unthankful",
    "unthinking", "unthread", "unthrift", "unthrifty", "untidy", "untie",
    "until", "untimely", "unto", "untold", "untouched", "untoward",
    "untrained", "untried", "untroubled", "untrue", "untrustworthy", "untruth",
    "untruthful", "untwine", "untwist", "unused", "unusual", "unutterable",
    "unvarnished", "unveil", "unviolated", "unwarlike", "unwarrantable", "unwarranted",
    "unwary", "unwashed", "unwavering", "unwearied", "unwell", "unwept",
    "unwholesome", "unwieldy", "unwilling", "unwillingness", "unwind", "unwise",
    "unwittingly", "unwonted", "unworthy", "unwrap", "unwritten", "unyielding",
    "unyoke", "up", "upbraid", "upcast", "upheaval", "upheave",
    "uphill", "uphold", "upholder", "upholsterer", "upholstery", "upkeep",
    "upland", "uplift", "upon", "upper", "uppermost", "upraise",
    "upright", "uprising", "uproar", "uproarious", "uproot", "upset",
    "upset", "upshot", "upside", "upside-down", "upstairs", "upstart",
    "upward", "upwards", "uranus", "urban", "urbane", "urbanity",
    "urchin", "urge", "urgency", "urgent", "urinal", "urine",
    "urn", "us", "usage", "use", "use", "useful",
    "useless", "user", "usher", "usual", "usurer", "usurious",
    "usurp", "usurpation", "usurper", "usury", "utensil", "uterine",
    "utilitarian", "utility", "utilize", "utmost", "utopia", "utopian",
    "utter", "utter", "utterance", "utterly", "uttermost", "uvula",
    "uxorious", "vacancy", "vacant", "vacate", "vacation", "vaccinate",
    "vaccination", "vaccine", "vacillate", "vacillation", "vacuity", "vacuous",
    "vacuum", "vagabond", "vagary", "vagina", "vagrancy", "vagrant",
    "vague", "vain", "vainly", "valance", "vale", "valediction",
    "valedictory", "valeriana", "valet", "valetudinarian", "valiant", "valid",
    "validate", "validity", "valise", "valley", "valor", "valorous",
    "valour", "valuable", "valuation", "value", "valueless", "valve",
    "vamp", "vampire", "van", "van", "vandal", "vandalism",
    "vandyke", "vane", "vanguard", "vanilla", "vanish", "vanity",
    "vanquish", "vantage", "vapid", "vapor", "vaporize", "vapour",
    "variable", "variance", "variant", "variation", "varicose", "variegated",
    "variety", "variola", "various", "varnish", "vary", "vase",
    "vaseline", "vassal", "vassalage", "vast", "vastly", "vat",
    "vatican", "vault", "vault", "vaulted", "vaunt", "veal",
    "vedas", "veer", "vegetable", "vegetarian", "vegetate", "vegetation",
    "vehemence", "vehement", "vehicle", "veil", "vein", "veined",
    "veiny", "vellum", "velocity", "velvet", "velveteen", "velvety",
    "venal", "venality", "vend", "vender", "vendor", "vendetta",
    "veneer", "venerable", "venerate", "veneration", "venereal", "venetian",
    "vengeance", "vengeful", "venial", "venison", "venom", "venomous",
    "venous", "vent", "vent", "ventilate", "ventilation", "ventilator",
    "ventral", "ventricle", "ventriloquism", "ventriloquist", "venture", "venturesome",
    "venturous", "venus", "veracity", "veranda", "verb", "verbal",
    "verbatim", "verbena", "verbiage", "verbose", "verbosity", "verdant",
    "verdict", "verdigris", "verdure", "verge", "verge", "verify",
    "verily", "verisimilitude", "veritable", "verity", "vermicelli", "vermicular",
    "vermifuge", "vermilion", "vermin", "vernacular", "vernal", "versatile",
    "versatility", "verse", "versed", "versification", "versifier", "versify",
    "version", "versus", "vertebra", "vertebrate", "vertex", "vertical",
    "vertigo", "vervain", "very", "vesicle", "vespers", "vessel",
    "vest", "vest", "vestal", "vestibule", "vestige", "vestment",
    "vestry", "vesture", "vetch", "veteran", "veterinary", "veto",
    "vex", "vexation", "vexatious", "viaduct", "vial", "viands",
    "viaticum", "vibrate", "vibration", "vicar", "vicarage", "vicarious",
    "vice", "vice", "vice-admiral", "vicegerent", "viceroy", "vicinity",
    "vicious", "vicissitude", "victim", "victimize", "victor", "victoria",
    "victorious", "victory", "victual", "victualer", "vidette", "vie",
    "view", "viewless", "vigil", "vigilance", "vigilant", "vignette",
    "vigor", "vigorous", "vigour", "vile", "vilify", "villa",
    "village", "villager", "villain", "villainous", "villainy", "vindicate",
    "vindication", "vindicative", "vindictive", "vine", "vinegar", "vineyard",
    "vintage", "vintner", "viol", "viola", "violate", "violation",
    "violence", "violent", "violet", "violin", "violinist", "violoncello",
    "viper", "viperous", "virago", "virgin", "virginal", "virginity",
    "virgo", "virile", "virility", "virtual", "virtually", "virtue",
    "virtuoso", "virtuous", "virulence", "virulent", "virus", "visage",
    "vis-a-vis", "viscera", "viscid", "viscosity", "viscount", "viscountess",
    "viscous", "visible", "vision", "visionary", "visit", "visitation",
    "visitor", "visor", "vista", "visual", "vital", "vitality",
    "vitalize", "vitiate", "vitreous", "vitrify", "vitriol", "vituperate",
    "vituperation", "vivacious", "vivacity", "vivid", "vivify", "vivisection",
    "vixen", "vizier", "vocabulary", "vocal", "vocalist", "vocation",
    "vociferate", "vociferous", "vogue", "voice", "voiceless", "void",
    "volatile", "volcanic", "volcano", "volition", "volley", "volt",
    "volubility", "voluble", "volume", "voluminous", "voluntary", "volunteer",
    "voluptuous", "volute", "vomit", "voracious", "voracity", "vortex",
    "votary", "vote", "voter", "votive", "vouch", "voucher",
    "vouchsafe", "vow", "vowel", "voyage", "voyager", "vulcanite",
    "vulgar", "vulgarism", "vulgarity", "vulgarize", "vulnerable", "vulture",
    "wadding", "waddle", "wade", "wader", "wafer", "waffle",
    "waft", "wag", "wage", "wager", "waggish", "waggle",
    "wagon", "wagoner", "wagtail", "waif", "wail", "wain",
    "wainscot", "waist", "waistband", "waistcoat", "wait", "waiter",
    "waiting-room", "waitress", "waive", "wake", "wake", "wakeful",
    "waken", "walk", "walker", "wall", "wallflower", "wall-fruit",
    "gallop", "wallow", "walnut", "walrus", "waltz", "wan",
    "wand", "wander", "wanderer", "wane", "want", "wanton",
    "war", "warble", "warbler", "ward", "ward", "warden",
    "warder", "wardrobe", "warehouse", "warfare", "warlike", "warm",
    "warmly", "warmth", "warn", "warning", "warp", "warrant",
    "warrant-officer", "warranty", "warren", "warrior", "wart", "wary",
    "was", "wash", "washerwoman", "washy", "wasp", "waspish",
    "waste", "wasteful", "watch", "watch", "watcher", "watchful",
    "watchmaker", "watchman", "watchword", "water", "watercress", "waterfall",
    "water-lily", "waterman", "watermelon", "waterproof", "water-spout", "waterworks",
    "watery", "wattle", "wattle", "wave", "wave", "waver",
    "wavy", "wax", "wax", "waxen", "waxwork", "way",
    "wayfarer", "waylay", "wayside", "wayward", "we", "weak",
    "weaken", "weakly", "weakness", "weal", "wealth", "wealthy",
    "wean", "weapon", "wear", "wear", "wearer", "weary",
    "wearisome", "weasel", "weather", "weathercock", "weather-glass", "weave",
    "weaver", "web", "webbed", "wed", "wedding", "wedge",
    "wedlock", "wednesday", "wee", "weed", "weedy", "week",
    "weekday", "weekly", "weep", "weeper", "weevil", "weft",
    "weigh", "weight", "weighty", "weir", "weird", "welcome",
    "weld", "welfare", "welkin", "well", "well", "well-being",
    "well-born", "well-bred", "welsh", "welt", "welter", "wen",
    "wench", "went", "wept", "were", "west", "westerly",
    "western", "westward", "wet", "wet-nurse", "whale", "whalebone",
    "whaler", "wharf", "wharfinger", "what", "whatever", "whatsoever",
    "wheat", "wheatear", "wheaten", "wheedle", "wheel", "wheelbarrow",
    "wheelwright", "wheeze", "whelk", "whelp", "when", "whence",
    "whenever", "where", "whereabouts", "whereas", "whereby", "wherefore",
    "whereinn", "whereof", "whereon", "whereto", "whereupon", "wherever",
    "wherewith", "wherry", "whet", "whether", "whey", "which",
    "whicheever", "whiff", "whig", "while", "while", "whilom",
    "whim", "whimper", "whimsical", "whin", "whine", "whip",
    "whippet", "whip-round", "whir", "whirl", "whirligig", "whirlpool",
    "whirlwind", "whirr", "whisk", "whisker", "whisky", "whisper",
    "whist", "whistle", "whistler", "whit", "white", "whitebait",
    "whiten", "white-throat", "whitewash", "whither", "whiting", "whitish",
    "whitleather", "whitlow", "whitsuntide", "whittle", "whity-brown", "whiz",
    "who", "whoever", "whole", "wholesale", "wholesome", "wholly",
    "whom", "whoop", "whooping-cough", "whortleberry", "whose", "why",
    "wick", "wicked", "wickedness", "wicker", "wicket", "wide",
    "widely", "widen", "widow", "widower", "widowhood", "width",
    "wield", "wife", "wig", "wight", "wigwam", "wild",
    "wilderness", "wildly", "wile", "wilful", "will", "will",
    "will", "willing", "willingly", "willow", "wily", "wimble",
    "win", "wince", "winch", "wind", "wind", "windlass",
    "windmill", "window", "windpipe", "windward", "windy", "wine",
    "wing", "winged", "wink", "winner", "winning", "winnow",
    "winsome", "winter", "wintry", "wipe", "wiper", "wire",
    "wiry", "wisdom", "wise", "wise", "wiseacre", "wisely",
    "wish", "wishful", "wisp", "wistful", "wit", "witch",
    "witchcraft", "witch-elm", "witch-hazel", "with", "withdraw", "withdrawal",
    "withe", "wither", "withers", "withhold", "within", "without",
    "withstand", "witless", "witness", "witticism", "witty", "wive",
    "wizard", "wizen", "woad", "wobble", "woe", "woebegone",
    "woeful", "wold", "wolf", "wolfsbane", "woman", "womanhood",
    "womanish", "womanly", "womb", "won", "wonder", "wonderful",
    "wonderment", "wondrous", "wont", "wonted", "woo", "wood",
    "woodbine", "woodcock", "woodcut", "wooded", "wooden", "woodland",
    "woodman", "woodpecker", "wood-pigeon", "woodruff", "woodwork", "woody",
    "wool", "woolen", "woolpack", "woolsack", "wooly", "word",
    "wordbook", "wordy", "wore", "work", "workhouse", "workman",
    "workshop", "world", "worldliness", "worldly", "worm", "wormwood",
    "worn", "worry", "worse", "worship", "worshiper", "worshipful",
    "worst", "worsted", "worth", "worthily", "worthiness", "worthless",
    "worthy", "would", "wound", "wound", "wove", "woven",
    "wrack", "wraith", "wrangle", "wrap", "wrapper", "wrath",
    "wrathful", "wreak", "wreath", "wreathe", "wreck", "wreckage",
    "wrecker", "wren", "wrench", "wrest", "wrestle", "wrestler",
    "wretch", "wretched", "wretchedness", "wriggle", "wright", "wring",
    "wringer", "wrinkle", "wrinkle", "wrist", "wristband", "writ",
    "write", "writer", "writhe", "writing", "written", "wrong",
    "wrongful", "wroth", "wrought", "wrung", "wry", "wyvern",
    "yacht", "yachtsman", "yak", "yam", "yankee", "yard",
    "yard", "yardarm", "yarn", "yarn", "yarrow", "yawl",
    "yawn", "ye", "yea", "year", "yearbook", "yearling",
    "yearly", "yearn", "yeast", "yeasty", "yell", "yellow",
    "yellow-hammer", "yelp", "yeoman", "yeomanry", "yes", "yesterday",
    "yet", "yew", "yield", "yoke", "yokefellow", "yolk",
    "yon", "yonder", "yore", "you", "young", "youngster",
    "your", "yours", "yourself", "youth", "youthful", "yule",
    "zeal", "zealot", "zealous", "zebra", "zenith", "zephyr",
    "zero", "zest", "zinc", "zodiac", "zone", "zoology",
    "zoophyte", "zouave"
]

import hashlib

def get_stable_index(seed_str: str, max_val: int) -> int:
    h = hashlib.sha256(seed_str.encode()).hexdigest()
    return int(h, 16) % max_val

@router.get("/new")
@_rate_limit("30/minute")
def get_new_wordle(
    request: Request,
    level: int = None
):
    word = random.choice(WORD_LIST)
    
    puzzle_id = store_solution(word)
    
    res = {
        "puzzle_id": puzzle_id,
        "valid_words": WORD_LIST  # To check guesses in the frontend
    }
    
    if level is not None:
        level = max(1, min(level, 100))
        if level <= 30:
            max_guesses = 6
        elif level <= 60:
            max_guesses = 5
        elif level <= 80:
            max_guesses = 4
        else:
            max_guesses = 3
        res["level"] = level
        res["max_guesses"] = max_guesses
        
    return res

@router.get("/daily")
@_rate_limit("30/minute")
def get_daily_wordle(
    request: Request,
    date: str
):
    idx = get_stable_index(f"wordle-{date}", len(WORD_LIST))
    word = WORD_LIST[idx]
    
    puzzle_id = store_solution(word)
    
    return {
        "puzzle_id": puzzle_id,
        "valid_words": WORD_LIST,
        "date": date
    }


class WordleGuessRequest(BaseModel):
    puzzle_id: str
    guess: str


@router.post("/guess")
def guess_wordle(req: WordleGuessRequest):
    target = get_solution(req.puzzle_id)
    if target is None:
        raise HTTPException(status_code=404, detail="Puzzle not found or expired")
    guess = req.guess.lower()
    if len(guess) != len(target):
        raise HTTPException(status_code=400, detail="Guess must be the same length as the target word")
    # Build per-letter feedback
    feedback = []
    target_chars = list(target)
    # First pass: mark correct positions
    for i, ch in enumerate(guess):
        if ch == target_chars[i]:
            feedback.append("correct")
            target_chars[i] = None  # consumed
        else:
            feedback.append(None)
    # Second pass: mark present/absent
    for i, ch in enumerate(guess):
        if feedback[i] is not None:
            continue
        if ch in target_chars:
            feedback[i] = "present"
            target_chars[target_chars.index(ch)] = None  # consumed
        else:
            feedback[i] = "absent"
    correct = all(f == "correct" for f in feedback)
    res_dict = {"feedback": feedback, "correct": correct}
    if correct:
        # Anti-Cheat: Validate elapsed solve time (minimum 3 seconds)
        gen_time = get_generation_time(req.puzzle_id)
        if gen_time:
            elapsed = time.time() - gen_time
            if elapsed < 3.0:
                raise HTTPException(status_code=400, detail="Solve time too fast. Suspicious activity detected.")
        solve_token = create_solve_token(req.puzzle_id, "wordle")
        res_dict["solve_token"] = solve_token
    return res_dict


@router.get("/solution")
def get_wordle_solution(puzzle_id: str):
    target = get_solution(puzzle_id)
    if target is None:
        raise HTTPException(status_code=404, detail="Puzzle not found or expired")
    remove_solution(puzzle_id)
    return {"solution": target.upper()}

